# Generated by Django 4.2.16 on 2024-10-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelformapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='traveldate',
            new_name='TravelDate',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travelfrom',
            new_name='TravelFrom',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='travelto',
            new_name='TravelTo',
        ),
    ]
