# Generated by Django 4.2.16 on 2024-10-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelformapp', '0002_rename_email_travel_email_rename_name_travel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='TravelDate',
            new_name='traveldate',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='TravelFrom',
            new_name='travelfrom',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='TravelTo',
            new_name='travelto',
        ),
    ]
